import Link from "next/link";
import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Image Credits",
  description: "Known image credits and current rights-verification status for visual assets used by Daily Red Sea.",
  path: "/image-credits",
});

const credits = [
  { use: "Private Luxor day trip", work: "Luxor Valley of the Kings", creator: "Wouter Hagens", source: "https://commons.wikimedia.org/wiki/File:Luxor_Valley_of_the_Kings_D.jpg", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/" },
  { use: "Luxor tour gallery", work: "The Great Hypostyle Hall, Karnak Temple", creator: "Warren LeMay", source: "https://commons.wikimedia.org/wiki/File:The_Great_Hypostyle_Hall,_Karnak_Temple,_Luxor,_LG,_EGY_(48009455531).jpg", license: "CC0", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/" },
  { use: "Orange Bay", work: "Hurghada Giftun Island Orange Bay", creator: "Mahmoudxx1", source: "https://commons.wikimedia.org/wiki/File:Hurghada_gifton_island_Orange_bay.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
  { use: "Mahmya Island", work: "Mahmya Island", creator: "Silar", source: "https://commons.wikimedia.org/wiki/File:02010_05712_Mahmya_Island.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
  { use: "Full-day snorkeling", work: "Hurghada snorkelling – Egypt", creator: "Fanny S Forsdik", source: "https://commons.wikimedia.org/wiki/File:Hurghada_snorkelling_-_Egypt_-_panoramio.jpg", license: "CC BY-SA 3.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/" },
  { use: "Full-day diving", work: "Scuba diving, Hurghada", creator: "Jerome Bon", source: "https://commons.wikimedia.org/wiki/File:Scuba_diving,_Hurghada_(2429616663).jpg", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/" },
  { use: "Underwater photographer", work: "Diver with camera at Gota Kebir, Red Sea", creator: "Derek Keats", source: "https://commons.wikimedia.org/wiki/File:Diver_with_camera_at_Gota_Kebir,_St_John%27s_reefs,_Red_Sea,_Egypt_-SCUBA_(6326262728).jpg", license: "CC BY 2.0", licenseUrl: "https://creativecommons.org/licenses/by/2.0/" },
  { use: "Desert safari and morning quad safari", work: "Desert Safari in Hurghada", creator: "Mostafa Abdel Samie", source: "https://commons.wikimedia.org/wiki/File:Desert_Safari_in_hurghada.jpg", license: "CC BY-SA 2.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/" },
  { use: "Sunset quad safari", work: "Dessert Safari", creator: "Norhan Elmaghrabi", source: "https://commons.wikimedia.org/wiki/File:Dessert_Safari.jpg", license: "CC BY-SA 4.0", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/" },
  { use: "Hurghada Airport transfer", work: "Hurghada Airport", creator: "Binter~commonswiki (attribution assumed by Commons)", source: "https://commons.wikimedia.org/wiki/File:Hurghada-Airport.jpg", license: "Public domain", licenseUrl: "https://commons.wikimedia.org/wiki/Commons:Public_domain" },
  { use: "Senzo Mall transfer", work: "Senzo Mall by night – Hurghada", creator: "Almondox", source: "https://commons.wikimedia.org/wiki/File:Senzo_Mall_(by_night)_-_Hurghada_-_panoramio.jpg", license: "CC BY 3.0", licenseUrl: "https://creativecommons.org/licenses/by/3.0/" },
];

export default function ImageCreditsPage() {
  return <main className="mx-auto max-w-5xl px-6 py-24 lg:px-8"><div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm sm:p-12"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-700">Rights and attribution register</p><h1 className="mt-4 text-4xl font-black text-slate-900">Image credits</h1><div className="mt-6 max-w-3xl space-y-4 text-lg leading-8 text-slate-600"><p>The records below document sources previously associated with particular website uses. They do not, by themselves, prove that every currently deployed local file is the exact credited work.</p><p className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-base text-amber-950">A per-file provenance review is in progress. Assets without an exact source, creator, license and binary match are treated internally as unverified and are not represented here as cleared stock or open-license photography.</p><p className="rounded-2xl border border-cyan-200 bg-cyan-50 p-4 text-base text-cyan-950">Current Dolphin House, diving, speedboat, Mahmya, Cairo/Giza, morning quad safari and Senzo Mall images were supplied by the Daily Red Sea owner on 12 August 2026 with confirmation of ownership and permission for website use. No third-party attribution is required. Wildlife sightings are never guaranteed.</p><p className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-base text-slate-700">Original Daily Red Sea category illustrations remain in use where no supplied photograph accurately represents the exact product, including horse riding, sunset quad safari, wellness and El Gouna.</p></div><div className="mt-10 divide-y divide-slate-200">{credits.map((credit) => <article key={credit.use} className="grid gap-2 py-5 sm:grid-cols-[1fr_1.4fr_auto] sm:items-center"><div><h2 className="font-bold text-slate-900">{credit.use}</h2><p className="mt-1 text-sm text-slate-500">Previously recorded source: {credit.work}</p></div><p className="text-sm text-slate-700">Creator listed as {credit.creator}</p><div className="flex gap-3 text-sm font-bold"><a href={credit.source} target="_blank" rel="noreferrer" className="text-cyan-700 hover:underline">Recorded source</a><a href={credit.licenseUrl} target="_blank" rel="noreferrer" className="text-blue-700 hover:underline">{credit.license}</a></div></article>)}</div><Link href="/" className="mt-10 inline-flex text-sm font-semibold text-cyan-700">← Back to home</Link></div></main>;
}
