import type { Locale } from "@/lib/i18n";
import type { DestinationSlug } from "@/lib/destinations";

export type DestinationCopy = {
  title: string; description: string; eyebrow: string; heading: string; categories: string;
  bookable: string; trips: (count: number) => string; otherDestinations: string;
  experiences: string; imageAlt: string;
};

export const hurghadaCopy: Record<Locale, DestinationCopy> = {
  en: { title: "Things to do in Hurghada", description: "Explore Hurghada tours, island trips, snorkeling, diving, desert safaris, historical excursions and private transfers with clear prices and local support.", eyebrow: "Egypt · Red Sea Governorate", heading: "Things to do in Hurghada", categories: "Explore by category", bookable: "Bookable Hurghada experiences", trips: (count) => `${count} trips with destination-specific pricing, schedules and pickup information.`, otherDestinations: "Explore other Red Sea destinations", experiences: "experiences", imageAlt: "Hurghada marina and mosque on Egypt's Red Sea coast" },
  ar: { title: "أفضل الأنشطة والرحلات في الغردقة", description: "استكشف رحلات الغردقة والجزر والسنوركلينج والغوص وسفاري الصحراء والرحلات التاريخية والتنقلات الخاصة بأسعار واضحة ودعم محلي.", eyebrow: "مصر · محافظة البحر الأحمر", heading: "أفضل الأنشطة في الغردقة", categories: "استكشف حسب الفئة", bookable: "رحلات متاحة للحجز في الغردقة", trips: (count) => `${count} رحلات بأسعار ومواعيد وتفاصيل استلام خاصة بالغردقة.`, otherDestinations: "استكشف وجهات أخرى على البحر الأحمر", experiences: "رحلات", imageAlt: "مرسى ومسجد الغردقة على ساحل البحر الأحمر في مصر" },
  de: { title: "Aktivitäten in Hurghada am Roten Meer", description: "Entdecke Ausflüge, Inseltouren, Schnorcheln, Tauchen, Wüstensafaris, historische Touren und private Transfers in Hurghada mit klaren Preisen und lokalem Support.", eyebrow: "Ägypten · Gouvernement Rotes Meer", heading: "Aktivitäten in Hurghada", categories: "Nach Kategorie entdecken", bookable: "Buchbare Erlebnisse in Hurghada", trips: (count) => `${count} Ausflüge mit Preisen, Zeiten und Abholinformationen für Hurghada.`, otherDestinations: "Weitere Reiseziele am Roten Meer", experiences: "Erlebnisse", imageAlt: "Marina und Moschee von Hurghada an Ägyptens Küste des Roten Meeres" },
  ru: { title: "Отдых и экскурсии в Хургаде на Красном море", description: "Изучите туры, островные поездки, снорклинг, дайвинг, пустынное сафари, исторические экскурсии и частные трансферы в Хургаде с понятными ценами и местной поддержкой.", eyebrow: "Египет · губернаторство Красное Море", heading: "Чем заняться в Хургаде", categories: "Выберите категорию", bookable: "Экскурсии в Хургаде", trips: (count) => `${count} экскурсии с ценами, расписанием и условиями трансфера для Хургады.`, otherDestinations: "Другие направления Красного моря", experiences: "экскурсии", imageAlt: "Марина и мечеть Хургады на побережье Красного моря в Египте" },
  pl: { title: "Atrakcje w Hurghadzie nad Morzem Czerwonym", description: "Odkryj wycieczki, rejsy na wyspy, snorkeling, nurkowanie, pustynne safari, wycieczki historyczne i prywatne transfery w Hurghadzie z jasnymi cenami i lokalnym wsparciem.", eyebrow: "Egipt · Prowincja Morza Czerwonego", heading: "Co robić w Hurghadzie", categories: "Przeglądaj według kategorii", bookable: "Atrakcje do rezerwacji w Hurghadzie", trips: (count) => `${count} wycieczki z cenami, harmonogramem i odbiorem właściwymi dla Hurghady.`, otherDestinations: "Poznaj inne miejsca nad Morzem Czerwonym", experiences: "atrakcje", imageAlt: "Marina i meczet w Hurghadzie na wybrzeżu Morza Czerwonego w Egipcie" },
  zh: { title: "赫尔格达红海旅游与本地体验 | Daily Red Sea", description: "探索赫尔格达的旅游项目、海岛之旅、浮潜、深潜、沙漠探险、历史游览和私人接送，价格透明，提供本地支持。", eyebrow: "埃及 · 红海省", heading: "赫尔格达旅游体验", categories: "按类别探索", bookable: "可预订的赫尔格达体验", trips: (count) => `${count} 个行程，提供赫尔格达专属价格、班期和接送信息。`, otherDestinations: "探索其他红海目的地", experiences: "个体验", imageAlt: "埃及红海海岸的赫尔格达码头与清真寺" },
};

export const marsaAlamCopy: Record<Locale, DestinationCopy> = {
  en: { title: "Things to do in Marsa Alam and the Red Sea", description: "Book Marsa Alam snorkeling trips to Dolphin House, Marsa Mubarak and Abu Dabbab with clear EUR prices, included hotel pickup and local support.", eyebrow: "Egypt · Red Sea Governorate", heading: "Things to do in Marsa Alam", categories: "Explore by category", bookable: "Bookable Marsa Alam experiences", trips: (count) => `${count} trips with destination-specific pricing, schedules and pickup information.`, otherDestinations: "Explore other Red Sea destinations", experiences: "experiences", imageAlt: "Marsa Alam reefs on Egypt's southern Red Sea coast" },
  ar: { title: "أفضل الأنشطة والرحلات في مرسى علم والبحر الأحمر", description: "احجز رحلات السنوركلينج من مرسى علم إلى دولفين هاوس ومرسى مبارك وأبو دباب بأسعار واضحة باليورو واستلام مشمول من الفنادق المحددة.", eyebrow: "مصر · محافظة البحر الأحمر", heading: "أفضل الأنشطة في مرسى علم", categories: "استكشف حسب الفئة", bookable: "رحلات متاحة للحجز في مرسى علم", trips: (count) => `${count} رحلات بأسعار ومواعيد وتفاصيل استلام خاصة بمرسى علم.`, otherDestinations: "استكشف وجهات أخرى على البحر الأحمر", experiences: "رحلات", imageAlt: "شعاب مرسى علم على ساحل البحر الأحمر في مصر" },
  de: { title: "Aktivitäten in Marsa Alam am Roten Meer", description: "Buche Schnorchelausflüge ab Marsa Alam zum Dolphin House, nach Marsa Mubarak und Abu Dabbab mit klaren EUR-Preisen und inklusive Hotelabholung.", eyebrow: "Ägypten · Gouvernement Rotes Meer", heading: "Aktivitäten in Marsa Alam", categories: "Nach Kategorie entdecken", bookable: "Buchbare Erlebnisse in Marsa Alam", trips: (count) => `${count} Ausflüge mit Preisen, Zeiten und Abholinformationen für Marsa Alam.`, otherDestinations: "Weitere Reiseziele am Roten Meer", experiences: "Erlebnisse", imageAlt: "Riffe von Marsa Alam an Ägyptens südlicher Küste des Roten Meeres" },
  ru: { title: "Отдых и экскурсии в Марса-Аламе на Красном море", description: "Бронируйте сноркелинг из Марса-Алама в Дом дельфинов, Марса-Мубарак и Абу-Даббаб: цены в EUR и трансфер из указанных отелей включён.", eyebrow: "Египет · губернаторство Красное Море", heading: "Чем заняться в Марса-Аламе", categories: "Выберите категорию", bookable: "Экскурсии в Марса-Аламе", trips: (count) => `${count} экскурсии с ценами, расписанием и условиями трансфера для Марса-Алама.`, otherDestinations: "Другие направления Красного моря", experiences: "экскурсии", imageAlt: "Рифы Марса-Алама на южном побережье Красного моря в Египте" },
  pl: { title: "Atrakcje w Marsa Alam nad Morzem Czerwonym", description: "Rezerwuj snorkeling z Marsa Alam do Dolphin House, Marsa Mubarak i Abu Dabbab: jasne ceny w EUR oraz odbiór z wybranych hoteli w cenie.", eyebrow: "Egipt · Prowincja Morza Czerwonego", heading: "Co robić w Marsa Alam", categories: "Przeglądaj według kategorii", bookable: "Atrakcje do rezerwacji w Marsa Alam", trips: (count) => `${count} wycieczki z cenami, harmonogramem i odbiorem właściwymi dla Marsa Alam.`, otherDestinations: "Poznaj inne miejsca nad Morzem Czerwonym", experiences: "atrakcje", imageAlt: "Rafy Marsa Alam na południowym wybrzeżu Morza Czerwonego w Egipcie" },
  zh: { title: "马萨阿拉姆红海旅游、浮潜与自然体验 | Daily Red Sea", description: "预订马萨阿拉姆出发的海豚屋、穆巴拉克湾和阿布达巴布浮潜行程，欧元价格清晰，并包含指定酒店接送。", eyebrow: "埃及 · 红海省", heading: "马萨阿拉姆旅游体验", categories: "按类别探索", bookable: "可预订的马萨阿拉姆体验", trips: (count) => `${count} 个行程，提供马萨阿拉姆专属价格、班期和接送信息。`, otherDestinations: "探索其他红海目的地", experiences: "个体验", imageAlt: "埃及红海南部海岸的马萨阿拉姆珊瑚礁" },
};

export const jeddahCopy: Record<Locale, DestinationCopy> = {
  en: { title: "Things to do in Jeddah", description: "Book Jeddah Red Sea experiences including try-scuba diving with clear SAR prices and local support.", eyebrow: "Saudi Arabia · Makkah Province", heading: "Things to do in Jeddah", categories: "Explore by category", bookable: "Bookable Jeddah experiences", trips: (count) => `${count} trips with destination-specific pricing, schedules and pickup information.`, otherDestinations: "Explore other Red Sea destinations", experiences: "experiences", imageAlt: "Jeddah Red Sea coastline in Saudi Arabia" },
  ar: { title: "أفضل الأنشطة والرحلات في جدة", description: "احجز تجارب جدة على البحر الأحمر، بما في ذلك تجربة الغوص التجريبي، بأسعار واضحة بالريال السعودي ودعم محلي.", eyebrow: "المملكة العربية السعودية · منطقة مكة المكرمة", heading: "أفضل الأنشطة في جدة", categories: "استكشف حسب الفئة", bookable: "رحلات متاحة للحجز في جدة", trips: (count) => `${count} رحلات بأسعار ومواعيد وتفاصيل استلام خاصة بجدة.`, otherDestinations: "استكشف وجهات أخرى على البحر الأحمر", experiences: "رحلات", imageAlt: "ساحل البحر الأحمر في جدة بالمملكة العربية السعودية" },
  de: { title: "Aktivitäten in Jeddah am Roten Meer", description: "Buche Erlebnisse in Jeddah am Roten Meer, darunter Schnupper-Tauchen, mit klaren SAR-Preisen und lokalem Support.", eyebrow: "Saudi-Arabien · Provinz Mekka", heading: "Aktivitäten in Jeddah", categories: "Nach Kategorie entdecken", bookable: "Buchbare Erlebnisse in Jeddah", trips: (count) => `${count} Ausflüge mit Preisen, Zeiten und Abholinformationen für Jeddah.`, otherDestinations: "Weitere Reiseziele am Roten Meer", experiences: "Erlebnisse", imageAlt: "Küste des Roten Meeres in Jeddah, Saudi-Arabien" },
  ru: { title: "Отдых и экскурсии в Джидде на Красном море", description: "Бронируйте экскурсии в Джидде на Красном море, включая пробный дайвинг, с понятными ценами в SAR и местной поддержкой.", eyebrow: "Саудовская Аравия · провинция Мекка", heading: "Чем заняться в Джидде", categories: "Выберите категорию", bookable: "Экскурсии в Джидде", trips: (count) => `${count} экскурсии с ценами, расписанием и условиями трансфера для Джидды.`, otherDestinations: "Другие направления Красного моря", experiences: "экскурсии", imageAlt: "Побережье Красного моря в Джидде, Саудовская Аравия" },
  pl: { title: "Atrakcje w Dżuddzie nad Morzem Czerwonym", description: "Rezerwuj atrakcje w Dżuddzie nad Morzem Czerwonym, w tym nurkowanie próbne, z jasnymi cenami w SAR i lokalnym wsparciem.", eyebrow: "Arabia Saudyjska · Prowincja Mekka", heading: "Co robić w Dżuddzie", categories: "Przeglądaj według kategorii", bookable: "Atrakcje do rezerwacji w Dżuddzie", trips: (count) => `${count} wycieczki z cenami, harmonogramem i odbiorem właściwymi dla Dżuddy.`, otherDestinations: "Poznaj inne miejsca nad Morzem Czerwonym", experiences: "atrakcje", imageAlt: "Wybrzeże Morza Czerwonego w Dżuddzie w Arabii Saudyjskiej" },
  zh: { title: "吉达红海旅游与本地体验 | Daily Red Sea", description: "预订吉达红海体验项目，包括体验潜水，沙特里亚尔价格透明，提供本地支持。", eyebrow: "沙特阿拉伯 · 麦加省", heading: "吉达旅游体验", categories: "按类别探索", bookable: "可预订的吉达体验", trips: (count) => `${count} 个行程，提供吉达专属价格、班期和接送信息。`, otherDestinations: "探索其他红海目的地", experiences: "个体验", imageAlt: "沙特阿拉伯吉达的红海海岸线" },
};

/** Central lookup for translated destination-page copy, keyed by destination slug. Destinations not listed here have no translated copy and fall back to English SEO fields. */
export const destinationCopyByLocale: Partial<Record<DestinationSlug, Record<Locale, DestinationCopy>>> = { hurghada: hurghadaCopy, "marsa-alam": marsaAlamCopy, jeddah: jeddahCopy };
