import type { Locale } from "@/lib/i18n";

export type DestinationCopy = {
  title: string; description: string; eyebrow: string; heading: string; categories: string;
  bookable: string; trips: (count: number) => string; otherDestinations: string;
  experiences: string; imageAlt: string;
};

export const marsaAlamCopy: Record<Locale, DestinationCopy> = {
  en: { title: "Things to do in Marsa Alam and the Red Sea", description: "Book Marsa Alam snorkeling trips to Dolphin House, Marsa Mubarak and Abu Dabbab with clear EUR prices, included hotel pickup and local support.", eyebrow: "Egypt · Red Sea Governorate", heading: "Things to do in Marsa Alam", categories: "Explore by category", bookable: "Bookable Marsa Alam experiences", trips: (count) => `${count} trips with destination-specific pricing, schedules and pickup information.`, otherDestinations: "Explore other Red Sea destinations", experiences: "experiences", imageAlt: "Marsa Alam reefs on Egypt's southern Red Sea coast" },
  ar: { title: "أفضل الأنشطة والرحلات في مرسى علم والبحر الأحمر", description: "احجز رحلات السنوركلينج من مرسى علم إلى دولفين هاوس ومرسى مبارك وأبو دباب بأسعار واضحة باليورو واستلام مشمول من الفنادق المحددة.", eyebrow: "مصر · محافظة البحر الأحمر", heading: "أفضل الأنشطة في مرسى علم", categories: "استكشف حسب الفئة", bookable: "رحلات متاحة للحجز في مرسى علم", trips: (count) => `${count} رحلات بأسعار ومواعيد وتفاصيل استلام خاصة بمرسى علم.`, otherDestinations: "استكشف وجهات أخرى على البحر الأحمر", experiences: "رحلات", imageAlt: "شعاب مرسى علم على ساحل البحر الأحمر في مصر" },
  de: { title: "Aktivitäten in Marsa Alam am Roten Meer", description: "Buche Schnorchelausflüge ab Marsa Alam zum Dolphin House, nach Marsa Mubarak und Abu Dabbab mit klaren EUR-Preisen und inklusive Hotelabholung.", eyebrow: "Ägypten · Gouvernement Rotes Meer", heading: "Aktivitäten in Marsa Alam", categories: "Nach Kategorie entdecken", bookable: "Buchbare Erlebnisse in Marsa Alam", trips: (count) => `${count} Ausflüge mit Preisen, Zeiten und Abholinformationen für Marsa Alam.`, otherDestinations: "Weitere Reiseziele am Roten Meer", experiences: "Erlebnisse", imageAlt: "Riffe von Marsa Alam an Ägyptens südlicher Küste des Roten Meeres" },
  ru: { title: "Отдых и экскурсии в Марса-Аламе на Красном море", description: "Бронируйте сноркелинг из Марса-Алама в Дом дельфинов, Марса-Мубарак и Абу-Даббаб: цены в EUR и трансфер из указанных отелей включён.", eyebrow: "Египет · губернаторство Красное Море", heading: "Чем заняться в Марса-Аламе", categories: "Выберите категорию", bookable: "Экскурсии в Марса-Аламе", trips: (count) => `${count} экскурсии с ценами, расписанием и условиями трансфера для Марса-Алама.`, otherDestinations: "Другие направления Красного моря", experiences: "экскурсии", imageAlt: "Рифы Марса-Алама на южном побережье Красного моря в Египте" },
  pl: { title: "Atrakcje w Marsa Alam nad Morzem Czerwonym", description: "Rezerwuj snorkeling z Marsa Alam do Dolphin House, Marsa Mubarak i Abu Dabbab: jasne ceny w EUR oraz odbiór z wybranych hoteli w cenie.", eyebrow: "Egipt · Prowincja Morza Czerwonego", heading: "Co robić w Marsa Alam", categories: "Przeglądaj według kategorii", bookable: "Atrakcje do rezerwacji w Marsa Alam", trips: (count) => `${count} wycieczki z cenami, harmonogramem i odbiorem właściwymi dla Marsa Alam.`, otherDestinations: "Poznaj inne miejsca nad Morzem Czerwonym", experiences: "atrakcje", imageAlt: "Rafy Marsa Alam na południowym wybrzeżu Morza Czerwonego w Egipcie" },
  zh: { title: "马萨阿拉姆红海旅游、浮潜与自然体验 | Daily Red Sea", description: "预订马萨阿拉姆出发的海豚屋、穆巴拉克湾和阿布达巴布浮潜行程，欧元价格清晰，并包含指定酒店接送。", eyebrow: "埃及 · 红海省", heading: "马萨阿拉姆旅游体验", categories: "按类别探索", bookable: "可预订的马萨阿拉姆体验", trips: (count) => `${count} 个行程，提供马萨阿拉姆专属价格、班期和接送信息。`, otherDestinations: "探索其他红海目的地", experiences: "个体验", imageAlt: "埃及红海南部海岸的马萨阿拉姆珊瑚礁" },
};
