import type { Locale } from "@/lib/i18n";

type SharedCopy = { soon: string; comingSoon: string; cart: string; currency: string; rates: string; ratesBy: string; follow: string; facebook: string; instagram: string; skip: string; openMenu: string; closeMenu: string; mobileNav: string; home: string; cookieTitle: string; cookieText: string; optionalCookies: string; analytics: string; marketing: string; reject: string; save: string; accept: string; whatsapp: string };

export const publicInterfaceCopy: Record<Locale, SharedCopy> = {
  en: { soon: "Soon", comingSoon: "Coming soon", cart: "trips in cart", currency: "Display currency", rates: "Rates", ratesBy: "Rates by Exchange Rate API", follow: "Follow Daily Red Sea", facebook: "Follow Daily Red Sea on Facebook", instagram: "Follow Daily Red Sea on Instagram", skip: "Skip to main content", openMenu: "Open navigation menu", closeMenu: "Close navigation menu", mobileNav: "Mobile navigation", home: "Daily Red Sea home", cookieTitle: "Your privacy choices", cookieText: "We use analytics to understand bookings and optional marketing tools to measure advertising. You can change your choice by clearing this site’s stored data in your browser.", optionalCookies: "Optional cookies", analytics: "Analytics", marketing: "Marketing", reject: "Reject optional", save: "Save choices", accept: "Accept all", whatsapp: "Hello Daily Red Sea 🌊 I would like information about your tours." },
  ar: { soon: "قريبًا", comingSoon: "قريبًا", cart: "رحلات في السلة", currency: "عملة العرض", rates: "الأسعار", ratesBy: "أسعار الصرف من Exchange Rate API", follow: "تابع ديلي رِد سي", facebook: "تابع ديلي رِد سي على فيسبوك", instagram: "تابع ديلي رِد سي على إنستغرام", skip: "انتقل إلى المحتوى الرئيسي", openMenu: "افتح قائمة التنقل", closeMenu: "أغلق قائمة التنقل", mobileNav: "قائمة التنقل للجوال", home: "الصفحة الرئيسية لديلي رِد سي", cookieTitle: "خيارات الخصوصية", cookieText: "نستخدم التحليلات لفهم الحجوزات وأدوات تسويق اختيارية لقياس الإعلانات. يمكنك تغيير اختيارك بمسح بيانات هذا الموقع المحفوظة في متصفحك.", optionalCookies: "ملفات تعريف الارتباط الاختيارية", analytics: "التحليلات", marketing: "التسويق", reject: "رفض الاختياري", save: "حفظ الخيارات", accept: "قبول الكل", whatsapp: "مرحبًا ديلي رِد سي 🌊 أود معرفة المزيد عن رحلاتكم." },
  de: { soon: "Bald", comingSoon: "Demnächst", cart: "Ausflüge im Warenkorb", currency: "Anzeigewährung", rates: "Kurse", ratesBy: "Kurse von Exchange Rate API", follow: "Daily Red Sea folgen", facebook: "Daily Red Sea auf Facebook folgen", instagram: "Daily Red Sea auf Instagram folgen", skip: "Zum Hauptinhalt springen", openMenu: "Navigationsmenü öffnen", closeMenu: "Navigationsmenü schließen", mobileNav: "Mobile Navigation", home: "Daily Red Sea Startseite", cookieTitle: "Deine Datenschutzauswahl", cookieText: "Wir nutzen Analysen, um Buchungen zu verstehen, und optionale Marketingtools zur Werbemessung. Du kannst deine Auswahl ändern, indem du die gespeicherten Websitedaten im Browser löschst.", optionalCookies: "Optionale Cookies", analytics: "Analyse", marketing: "Marketing", reject: "Optionale ablehnen", save: "Auswahl speichern", accept: "Alle akzeptieren", whatsapp: "Hallo Daily Red Sea 🌊 Ich möchte Informationen zu euren Ausflügen." },
  ru: { soon: "Скоро", comingSoon: "Скоро", cart: "экскурсий в корзине", currency: "Валюта отображения", rates: "Курсы", ratesBy: "Курсы от Exchange Rate API", follow: "Подписаться на Daily Red Sea", facebook: "Daily Red Sea в Facebook", instagram: "Daily Red Sea в Instagram", skip: "Перейти к основному содержанию", openMenu: "Открыть меню навигации", closeMenu: "Закрыть меню навигации", mobileNav: "Мобильная навигация", home: "Главная Daily Red Sea", cookieTitle: "Настройки конфиденциальности", cookieText: "Мы используем аналитику для изучения бронирований и необязательные маркетинговые инструменты для оценки рекламы. Изменить выбор можно, удалив сохранённые данные сайта в браузере.", optionalCookies: "Необязательные файлы cookie", analytics: "Аналитика", marketing: "Маркетинг", reject: "Отклонить необязательные", save: "Сохранить выбор", accept: "Принять все", whatsapp: "Здравствуйте, Daily Red Sea 🌊 Я хочу узнать о ваших экскурсиях." },
  pl: { soon: "Wkrótce", comingSoon: "Wkrótce", cart: "wycieczek w koszyku", currency: "Wyświetlana waluta", rates: "Kursy", ratesBy: "Kursy z Exchange Rate API", follow: "Obserwuj Daily Red Sea", facebook: "Obserwuj Daily Red Sea na Facebooku", instagram: "Obserwuj Daily Red Sea na Instagramie", skip: "Przejdź do głównej treści", openMenu: "Otwórz menu nawigacji", closeMenu: "Zamknij menu nawigacji", mobileNav: "Nawigacja mobilna", home: "Strona główna Daily Red Sea", cookieTitle: "Ustawienia prywatności", cookieText: "Używamy analityki, aby rozumieć rezerwacje, oraz opcjonalnych narzędzi marketingowych do mierzenia reklam. Wybór możesz zmienić, usuwając zapisane dane tej witryny w przeglądarce.", optionalCookies: "Opcjonalne pliki cookie", analytics: "Analityka", marketing: "Marketing", reject: "Odrzuć opcjonalne", save: "Zapisz wybór", accept: "Zaakceptuj wszystkie", whatsapp: "Dzień dobry Daily Red Sea 🌊 Chcę uzyskać informacje o wycieczkach." },
  zh: { soon: "即将推出", comingSoon: "即将推出", cart: "个项目在购物车中", currency: "显示货币", rates: "汇率", ratesBy: "汇率由 Exchange Rate API 提供", follow: "关注 Daily Red Sea", facebook: "在 Facebook 上关注 Daily Red Sea", instagram: "在 Instagram 上关注 Daily Red Sea", skip: "跳至主要内容", openMenu: "打开导航菜单", closeMenu: "关闭导航菜单", mobileNav: "移动端导航", home: "Daily Red Sea 首页", cookieTitle: "您的隐私选择", cookieText: "我们使用分析工具了解预订情况，并使用可选营销工具衡量广告效果。您可以清除浏览器中保存的本站数据来更改选择。", optionalCookies: "可选 Cookie", analytics: "分析", marketing: "营销", reject: "拒绝可选项", save: "保存选择", accept: "全部接受", whatsapp: "您好，Daily Red Sea 🌊 我想了解你们的旅游项目。" },
};

const badges: Record<Locale, Record<string, string>> = {
  en: { "Most Popular": "Most Popular", "Best Value": "Best Value", Premium: "Premium", New: "New", "Best Seller": "Best Seller" },
  ar: { "Most Popular": "الأكثر شعبية", "Best Value": "أفضل قيمة", Premium: "مميز", New: "جديد", "Best Seller": "الأكثر مبيعًا" },
  de: { "Most Popular": "Am beliebtesten", "Best Value": "Bestes Preis-Leistungs-Verhältnis", Premium: "Premium", New: "Neu", "Best Seller": "Bestseller" },
  ru: { "Most Popular": "Самое популярное", "Best Value": "Лучшая цена", Premium: "Премиум", New: "Новинка", "Best Seller": "Хит продаж" },
  pl: { "Most Popular": "Najpopularniejsze", "Best Value": "Najlepsza cena", Premium: "Premium", New: "Nowość", "Best Seller": "Bestseller" },
  zh: { "Most Popular": "最受欢迎", "Best Value": "超值之选", Premium: "尊享", New: "新品", "Best Seller": "热销" },
};

export function localizeProductBadge(locale: Locale, badge: string) { return badges[locale][badge] || badge; }
