import type { Locale } from "@/lib/i18n";

type ReferralCopy = {
  heading: string; tagline: string; yourCode: string; copyCode: string; copied: string; copyLink: string; shareWhatsapp: string;
  whatsappMessage: string; available: string; maxPerBooking: string; pending: string; qualified: string;
  emailOrPhoneLabel: string; sendCode: string; codeSentNotice: string; enterCodeLabel: string; verify: string; invalidCode: string;
  verifyIntro: string; applyPrompt: (percent: number) => string; applyButton: string; applied: string; noRewardsYet: string;
  checkoutCodeLabel: string; checkoutApply: string; checkoutRemove: string; checkoutDiscount: string; checkoutHint: string;
};

export const referralCopy: Record<Locale, ReferralCopy> = {
  en: { heading: "GIVE 5% — GET 5%", tagline: "Give friends 5% off their first eligible booking. After they complete their experience, you earn 5% off a future booking.", yourCode: "Your referral code", copyCode: "Copy code", copied: "Copied!", copyLink: "Copy referral link", shareWhatsapp: "Share on WhatsApp", whatsappMessage: "Explore the Red Sea with Daily Red Sea! Use my link and get 5% off your first eligible booking.", available: "Available rewards", maxPerBooking: "Maximum usable on one booking", pending: "Pending", qualified: "Successful referrals", emailOrPhoneLabel: "Email or WhatsApp number", sendCode: "Send verification code", codeSentNotice: "If that email or phone has referral rewards, we sent a 6-digit code.", enterCodeLabel: "Verification code", verify: "Verify", invalidCode: "That code is incorrect or has expired.", verifyIntro: "Verify your email or phone to view your referral code and rewards.", applyPrompt: (percent) => `You have ${percent}% in referral rewards. Apply it to this booking?`, applyButton: "Apply to this booking", applied: "Referral reward applied", noRewardsYet: "No referral rewards yet — share your link to start earning.", checkoutCodeLabel: "Referral code", checkoutApply: "Apply", checkoutRemove: "Remove", checkoutDiscount: "Referral discount", checkoutHint: "Have a friend's referral code? Enter it here." },
  ar: { heading: "امنح 5% — احصل على 5%", tagline: "امنح أصدقاءك خصم 5% على أول حجز مؤهل لهم. وبعد إتمام رحلتهم، تحصل أنت على خصم 5% لحجز قادم.", yourCode: "رمز الإحالة الخاص بك", copyCode: "نسخ الرمز", copied: "تم النسخ!", copyLink: "نسخ رابط الإحالة", shareWhatsapp: "مشاركة عبر واتساب", whatsappMessage: "اكتشف البحر الأحمر مع ديلي رِد سي! استخدم رابطي واحصل على خصم 5% على أول حجز مؤهل لك.", available: "المكافآت المتاحة", maxPerBooking: "الحد الأقصى للاستخدام في حجز واحد", pending: "قيد الانتظار", qualified: "الإحالات الناجحة", emailOrPhoneLabel: "البريد الإلكتروني أو رقم واتساب", sendCode: "إرسال رمز التحقق", codeSentNotice: "إذا كان لهذا البريد أو الرقم مكافآت إحالة، فقد أرسلنا رمزًا مكونًا من 6 أرقام.", enterCodeLabel: "رمز التحقق", verify: "تحقق", invalidCode: "الرمز غير صحيح أو منتهي الصلاحية.", verifyIntro: "تحقق من بريدك الإلكتروني أو هاتفك لعرض رمز الإحالة والمكافآت الخاصة بك.", applyPrompt: (percent) => `لديك ${percent}% من مكافآت الإحالة. هل تريد تطبيقها على هذا الحجز؟`, applyButton: "تطبيق على هذا الحجز", applied: "تم تطبيق مكافأة الإحالة", noRewardsYet: "لا توجد مكافآت إحالة بعد — شارك رابطك لتبدأ بالكسب.", checkoutCodeLabel: "رمز الإحالة", checkoutApply: "تطبيق", checkoutRemove: "إزالة", checkoutDiscount: "خصم الإحالة", checkoutHint: "هل لديك رمز إحالة من صديق؟ أدخله هنا." },
  de: { heading: "GIB 5% — ERHALTE 5%", tagline: "Gib Freunden 5% Rabatt auf ihre erste berechtigte Buchung. Nach ihrer Reise erhältst du 5% Rabatt auf eine künftige Buchung.", yourCode: "Dein Empfehlungscode", copyCode: "Code kopieren", copied: "Kopiert!", copyLink: "Empfehlungslink kopieren", shareWhatsapp: "Auf WhatsApp teilen", whatsappMessage: "Entdecke das Rote Meer mit Daily Red Sea! Nutze meinen Link und erhalte 5% Rabatt auf deine erste berechtigte Buchung.", available: "Verfügbare Prämien", maxPerBooking: "Maximal nutzbar pro Buchung", pending: "Ausstehend", qualified: "Erfolgreiche Empfehlungen", emailOrPhoneLabel: "E-Mail oder WhatsApp-Nummer", sendCode: "Bestätigungscode senden", codeSentNotice: "Falls diese E-Mail oder Nummer Empfehlungsprämien hat, haben wir einen 6-stelligen Code gesendet.", enterCodeLabel: "Bestätigungscode", verify: "Bestätigen", invalidCode: "Dieser Code ist falsch oder abgelaufen.", verifyIntro: "Bestätige deine E-Mail oder Telefonnummer, um deinen Empfehlungscode und deine Prämien zu sehen.", applyPrompt: (percent) => `Du hast ${percent}% Empfehlungsprämien. Auf diese Buchung anwenden?`, applyButton: "Auf diese Buchung anwenden", applied: "Empfehlungsprämie angewendet", noRewardsYet: "Noch keine Empfehlungsprämien — teile deinen Link, um zu verdienen.", checkoutCodeLabel: "Empfehlungscode", checkoutApply: "Anwenden", checkoutRemove: "Entfernen", checkoutDiscount: "Empfehlungsrabatt", checkoutHint: "Hast du den Empfehlungscode eines Freundes? Hier eingeben." },
  ru: { heading: "ПОДАРИ 5% — ПОЛУЧИ 5%", tagline: "Подарите друзьям скидку 5% на первое подходящее бронирование. После завершения их поездки вы получите скидку 5% на будущее бронирование.", yourCode: "Ваш реферальный код", copyCode: "Скопировать код", copied: "Скопировано!", copyLink: "Скопировать реферальную ссылку", shareWhatsapp: "Поделиться в WhatsApp", whatsappMessage: "Откройте для себя Красное море с Daily Red Sea! Используйте мою ссылку и получите скидку 5% на первое подходящее бронирование.", available: "Доступные вознаграждения", maxPerBooking: "Максимум на одно бронирование", pending: "В ожидании", qualified: "Успешные рефералы", emailOrPhoneLabel: "Email или номер WhatsApp", sendCode: "Отправить код подтверждения", codeSentNotice: "Если у этого email или номера есть реферальные вознаграждения, мы отправили 6-значный код.", enterCodeLabel: "Код подтверждения", verify: "Подтвердить", invalidCode: "Код неверен или истёк.", verifyIntro: "Подтвердите свой email или телефон, чтобы увидеть реферальный код и вознаграждения.", applyPrompt: (percent) => `У вас есть ${percent}% реферальных вознаграждений. Применить к этому бронированию?`, applyButton: "Применить к этому бронированию", applied: "Реферальное вознаграждение применено", noRewardsYet: "Пока нет реферальных вознаграждений — поделитесь ссылкой, чтобы начать зарабатывать.", checkoutCodeLabel: "Реферальный код", checkoutApply: "Применить", checkoutRemove: "Удалить", checkoutDiscount: "Реферальная скидка", checkoutHint: "Есть реферальный код друга? Введите его здесь." },
  pl: { heading: "DAJ 5% — ZYSKAJ 5%", tagline: "Daj znajomym 5% zniżki na pierwszą kwalifikującą się rezerwację. Po zakończeniu ich wycieczki ty zyskujesz 5% zniżki na kolejną rezerwację.", yourCode: "Twój kod polecający", copyCode: "Kopiuj kod", copied: "Skopiowano!", copyLink: "Kopiuj link polecający", shareWhatsapp: "Udostępnij w WhatsApp", whatsappMessage: "Odkryj Morze Czerwone z Daily Red Sea! Użyj mojego linku i zyskaj 5% zniżki na pierwszą kwalifikującą się rezerwację.", available: "Dostępne nagrody", maxPerBooking: "Maksymalnie do wykorzystania w jednej rezerwacji", pending: "Oczekujące", qualified: "Skuteczne polecenia", emailOrPhoneLabel: "E-mail lub numer WhatsApp", sendCode: "Wyślij kod weryfikacyjny", codeSentNotice: "Jeśli ten e-mail lub numer ma nagrody polecające, wysłaliśmy 6-cyfrowy kod.", enterCodeLabel: "Kod weryfikacyjny", verify: "Zweryfikuj", invalidCode: "Ten kod jest nieprawidłowy lub wygasł.", verifyIntro: "Zweryfikuj swój e-mail lub telefon, aby zobaczyć swój kod polecający i nagrody.", applyPrompt: (percent) => `Masz ${percent}% nagród polecających. Zastosować do tej rezerwacji?`, applyButton: "Zastosuj do tej rezerwacji", applied: "Nagroda polecająca zastosowana", noRewardsYet: "Brak jeszcze nagród polecających — udostępnij swój link, aby zacząć zarabiać.", checkoutCodeLabel: "Kod polecający", checkoutApply: "Zastosuj", checkoutRemove: "Usuń", checkoutDiscount: "Zniżka polecająca", checkoutHint: "Masz kod polecający znajomego? Wpisz go tutaj." },
  zh: { heading: "赠 5% — 得 5%", tagline: "邀请好友享受首次符合条件预订的 5% 折扣。好友完成行程后，您将获得未来预订的 5% 折扣。", yourCode: "您的推荐码", copyCode: "复制推荐码", copied: "已复制！", copyLink: "复制推荐链接", shareWhatsapp: "通过 WhatsApp 分享", whatsappMessage: "与 Daily Red Sea 一起探索红海！使用我的链接，即可在首次符合条件的预订中享受 5% 折扣。", available: "可用奖励", maxPerBooking: "单次预订最多可用", pending: "待定", qualified: "成功推荐", emailOrPhoneLabel: "电子邮件或 WhatsApp 号码", sendCode: "发送验证码", codeSentNotice: "如果该邮箱或号码有推荐奖励，我们已发送 6 位验证码。", enterCodeLabel: "验证码", verify: "验证", invalidCode: "验证码不正确或已过期。", verifyIntro: "验证您的邮箱或电话，以查看您的推荐码和奖励。", applyPrompt: (percent) => `您有 ${percent}% 的推荐奖励，是否应用到本次预订？`, applyButton: "应用到本次预订", applied: "已应用推荐奖励", noRewardsYet: "暂无推荐奖励——分享您的链接即可开始赚取。", checkoutCodeLabel: "推荐码", checkoutApply: "应用", checkoutRemove: "移除", checkoutDiscount: "推荐折扣", checkoutHint: "有朋友的推荐码？在此输入。" },
};
