import type { Locale } from "@/lib/i18n";

export const referralNotificationCopy: Record<Locale, { thanks: string; enjoyed: string; review: string; unlocked: string; earned: string; balance: (percent: number) => string; otpSubject: string; otpBody: string }> = {
  en: { thanks: "Thank you for travelling with Daily Red Sea", enjoyed: "We hope you enjoyed your experience. Thank you for choosing us!", review: "Share your experience — leave a review", unlocked: "Your referral program is unlocked", earned: "You've earned another 5% referral reward!", balance: p => `You now have ${p}% in rewards for future bookings. Use up to 15% per trip; the rest stays available.`, otpSubject: "Your Daily Red Sea verification code", otpBody: "Your code expires in 10 minutes. If you did not request it, you can ignore this email." },
  ar: { thanks: "شكراً لرحلتك مع ديلي رد سي", enjoyed: "نأمل أن تكون قد استمتعت بتجربتك. شكراً لاختيارك لنا!", review: "شارك تجربتك — اكتب تقييماً", unlocked: "تم تفعيل برنامج الإحالات الخاص بك", earned: "لقد كسبت مكافأة إحالة إضافية بنسبة 5%!", balance: p => `لديك الآن ${p}% كمكافآت للحجوزات القادمة. استخدم حتى 15% لكل رحلة ويبقى الباقي متاحاً.`, otpSubject: "رمز التحقق الخاص بك من ديلي رد سي", otpBody: "تنتهي صلاحية الرمز بعد 10 دقائق. إذا لم تطلبه، يمكنك تجاهل هذا البريد." },
  de: { thanks: "Danke für deine Reise mit Daily Red Sea", enjoyed: "Wir hoffen, dir hat dein Erlebnis gefallen. Danke, dass du uns gewählt hast!", review: "Teile dein Erlebnis — schreibe eine Bewertung", unlocked: "Dein Empfehlungsprogramm ist freigeschaltet", earned: "Du hast weitere 5% Empfehlungsprämie verdient!", balance: p => `Du hast jetzt ${p}% für künftige Buchungen. Nutze bis zu 15% pro Reise; der Rest bleibt verfügbar.`, otpSubject: "Dein Daily Red Sea Bestätigungscode", otpBody: "Dein Code läuft in 10 Minuten ab. Wenn du ihn nicht angefordert hast, ignoriere diese E-Mail." },
  ru: { thanks: "Спасибо за поездку с Daily Red Sea", enjoyed: "Надеемся, вам понравилось. Спасибо, что выбрали нас!", review: "Поделитесь впечатлениями — оставьте отзыв", unlocked: "Ваша реферальная программа открыта", earned: "Вы заработали ещё 5% реферальной скидки!", balance: p => `У вас ${p}% для будущих бронирований. Используйте до 15% за поездку; остаток сохраняется.`, otpSubject: "Ваш код подтверждения Daily Red Sea", otpBody: "Код действует 10 минут. Если вы его не запрашивали, проигнорируйте письмо." },
  pl: { thanks: "Dziękujemy za podróż z Daily Red Sea", enjoyed: "Mamy nadzieję, że wycieczka się podobała. Dziękujemy za wybranie nas!", review: "Podziel się wrażeniami — wystaw opinię", unlocked: "Twój program poleceń jest odblokowany", earned: "Zyskujesz kolejne 5% nagrody za polecenie!", balance: p => `Masz teraz ${p}% na przyszłe rezerwacje. Wykorzystaj do 15% na wycieczkę; reszta pozostaje dostępna.`, otpSubject: "Twój kod weryfikacyjny Daily Red Sea", otpBody: "Kod wygasa za 10 minut. Jeśli o niego nie prosisz, zignoruj tę wiadomość." },
  zh: { thanks: "感谢您与 Daily Red Sea 一起旅行", enjoyed: "希望您享受了这次体验。感谢您选择我们！", review: "分享您的体验——留下评价", unlocked: "您的推荐计划已解锁", earned: "您又获得了 5% 推荐奖励！", balance: p => `您现在有 ${p}% 的未来预订奖励。每次行程最多使用 15%，其余奖励保留。`, otpSubject: "您的 Daily Red Sea 验证码", otpBody: "验证码将在 10 分钟后失效。如果您未申请，请忽略此邮件。" },
};
