import type { Locale } from "@/lib/i18n";

const keys = ["pricing", "item", "quantity", "unit", "lineTotal", "adults", "youth", "infants", "booking", "vehicle", "extra", "entrance", "subtotal", "promo", "noPromo", "unknownPromo", "discount", "unknownPrices", "unknownParticipants", "pending", "guests", "inconsistent"] as const;
type PricingCopy = Record<typeof keys[number], string>;
const translations: Record<Locale, string[]> = {
  en: ["Price breakdown", "Category / item", "Quantity", "Unit price", "Line total", "Adults", "Children / youth", "Infants", "Per booking", "Vehicle / leg", "Extra", "Entrance", "Subtotal", "Promo code", "No promo code applied", "Promo history unavailable", "Discount", "Historical unit prices unavailable", "Participant categories unavailable", "Price to be confirmed", "Travelers", "Recorded pricing does not reconcile; contact us for clarification"],
  de: ["Preisübersicht", "Kategorie / Leistung", "Anzahl", "Einzelpreis", "Gesamt", "Erwachsene", "Kinder / Jugendliche", "Kleinkinder", "Pro Buchung", "Fahrzeug / Strecke", "Extra", "Eintritt", "Zwischensumme", "Aktionscode", "Kein Aktionscode angewendet", "Aktionsverlauf nicht verfügbar", "Rabatt", "Historische Einzelpreise nicht verfügbar", "Teilnehmerkategorien nicht verfügbar", "Preis wird bestätigt", "Reisende", "Gespeicherte Preise stimmen nicht überein; bitte kontaktiere uns"],
  ru: ["Расчёт стоимости", "Категория / услуга", "Кол-во", "Цена за ед.", "Сумма", "Взрослые", "Дети / подростки", "Младенцы", "За бронирование", "Автомобиль / маршрут", "Дополнение", "Вход", "Подытог", "Промокод", "Промокод не применён", "История промокода недоступна", "Скидка", "Исторические цены за единицу недоступны", "Категории участников недоступны", "Цена уточняется", "Участники", "Записанные цены не совпадают; свяжитесь с нами"],
  ar: ["تفاصيل الأسعار", "الفئة / البند", "العدد", "سعر الوحدة", "إجمالي البند", "البالغون", "الأطفال / الشباب", "الرضع", "لكل حجز", "المركبة / الاتجاه", "إضافة", "رسوم الدخول", "المجموع قبل الخصم", "رمز الخصم", "لم يتم تطبيق رمز خصم", "سجل رمز الخصم غير متاح", "الخصم", "أسعار الوحدات الأصلية غير متاحة", "فئات المشاركين غير متاحة", "سيتم تأكيد السعر", "المسافرون", "الأسعار المسجلة غير متطابقة؛ يرجى التواصل معنا"],
  pl: ["Zestawienie cen", "Kategoria / pozycja", "Liczba", "Cena jedn.", "Suma", "Dorośli", "Dzieci / młodzież", "Niemowlęta", "Za rezerwację", "Pojazd / przejazd", "Dodatek", "Wstęp", "Suma częściowa", "Kod promocyjny", "Nie zastosowano kodu", "Historia kodu niedostępna", "Rabat", "Historyczne ceny jednostkowe niedostępne", "Kategorie uczestników niedostępne", "Cena do potwierdzenia", "Podróżni", "Zapisane ceny są niespójne; skontaktuj się z nami"],
  zh: ["价格明细", "类别 / 项目", "数量", "单价", "项目总额", "成人", "儿童 / 青少年", "婴儿", "每笔预订", "车辆 / 单程", "附加项目", "门票", "折前小计", "优惠码", "未使用优惠码", "优惠码历史不可用", "折扣", "原始单价不可用", "参与者类别不可用", "价格待确认", "出行人数", "记录的价格不一致，请联系我们核实"],
};
export const statusPricingCopy = Object.fromEntries(Object.entries(translations).map(([locale, values]) => [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))])) as Record<Locale, PricingCopy>;
