import type { Locale } from "@/lib/i18n";

type ThankYouCopy = { memory: string; give: string; earn: string; heading: string; intro: string; reviews: string; reviewIntro: string; siteReview: string; googleReview: string; independent: string; next: (destination: string) => string; explore: string; signoff: string };

export const tripThankYouCopy: Record<Locale, ThankYouCopy> = {
  en: { give: "For your friends", earn: "For your next adventure", memory: "A little more Red Sea", heading: "Thank you for sharing the adventure.", intro: "We hope your trip left you with wonderful memories. It was a pleasure to have you with us.", reviews: "How was your experience?", reviewIntro: "Your honest review helps other travellers choose their next adventure and helps us improve. Share your trip experience on our site, and review Daily Red Sea on Google too.", siteReview: "Review your trip", googleReview: "Review us on Google", independent: "Reviews are optional. Referral rewards are separate and never depend on leaving a review or its rating.", next: d => `More to discover in ${d}`, explore: "Explore this trip", signoff: "Until your next adventure,\nThe Daily Red Sea team" },
  ar: { give: "لأصدقائك", earn: "لمغامرتك القادمة", memory: "المزيد من سحر البحر الأحمر", heading: "شكراً لمشاركتنا المغامرة.", intro: "نتمنى أن تكون رحلتك قد تركت ذكريات جميلة. سعدنا بوجودك معنا.", reviews: "كيف كانت تجربتك؟", reviewIntro: "تقييمك الصادق يساعد المسافرين على اختيار مغامرتهم القادمة ويساعدنا على التحسين. شارك تجربة رحلتك على موقعنا، وقيّم ديلي رد سي على Google أيضاً.", siteReview: "قيّم رحلتك", googleReview: "قيّمنا على Google", independent: "التقييم اختياري. مكافآت الإحالة مستقلة ولا تعتمد أبداً على كتابة تقييم أو عدد نجومه.", next: d => `اكتشف المزيد في ${d}`, explore: "اكتشف هذه الرحلة", signoff: "إلى مغامرتك القادمة،\nفريق ديلي رد سي" },
  de: { give: "Für deine Freunde", earn: "Für dein nächstes Abenteuer", memory: "Noch ein bisschen Rotes Meer", heading: "Danke für das gemeinsame Abenteuer.", intro: "Wir hoffen, du nimmst schöne Erinnerungen mit nach Hause. Es war uns eine Freude, dich dabei zu haben.", reviews: "Wie war dein Erlebnis?", reviewIntro: "Deine ehrliche Bewertung hilft anderen Reisenden bei der Auswahl und uns, besser zu werden. Bewerte deine Reise auf unserer Website und Daily Red Sea auch auf Google.", siteReview: "Deine Reise bewerten", googleReview: "Auf Google bewerten", independent: "Bewertungen sind freiwillig. Empfehlungsprämien sind unabhängig davon, ob und wie du eine Bewertung abgibst.", next: d => `Mehr entdecken in ${d}`, explore: "Diese Reise entdecken", signoff: "Bis zum nächsten Abenteuer,\nDein Daily Red Sea Team" },
  ru: { give: "Для ваших друзей", earn: "Для будущей поездки", memory: "Ещё немного Красного моря", heading: "Спасибо за совместное приключение.", intro: "Надеемся, поездка подарила вам прекрасные воспоминания. Мы были рады видеть вас с нами.", reviews: "Как прошла ваша поездка?", reviewIntro: "Честный отзыв помогает другим путешественникам сделать выбор, а нам — стать лучше. Поделитесь впечатлениями о поездке на нашем сайте и оцените Daily Red Sea в Google.", siteReview: "Оставить отзыв о поездке", googleReview: "Оставить отзыв в Google", independent: "Отзывы добровольны. Реферальные вознаграждения не зависят от наличия отзыва или его оценки.", next: d => `Другие поездки: ${d}`, explore: "Посмотреть поездку", signoff: "До новых приключений,\nКоманда Daily Red Sea" },
  pl: { give: "Dla Twoich znajomych", earn: "Na kolejną przygodę", memory: "Jeszcze trochę Morza Czerwonego", heading: "Dziękujemy za wspólną przygodę.", intro: "Mamy nadzieję, że wycieczka pozostawiła piękne wspomnienia. Miło było gościć Cię z nami.", reviews: "Jak oceniasz swoje wrażenia?", reviewIntro: "Twoja szczera opinia pomaga innym podróżnym wybrać przygodę, a nam się rozwijać. Oceń wycieczkę na naszej stronie oraz Daily Red Sea w Google.", siteReview: "Oceń swoją wycieczkę", googleReview: "Oceń nas w Google", independent: "Opinie są dobrowolne. Nagrody za polecenia są niezależne od wystawienia opinii i jej oceny.", next: d => `Odkryj więcej: ${d}`, explore: "Zobacz wycieczkę", signoff: "Do następnej przygody,\nZespół Daily Red Sea" },
  zh: { give: "送给好友", earn: "用于下次冒险", memory: "再享一点红海时光", heading: "感谢您与我们一起探索。", intro: "希望这次旅行为您留下美好的回忆。很高兴有您同行。", reviews: "您的体验如何？", reviewIntro: "您的真实评价能帮助其他旅客选择行程，也帮助我们改进服务。欢迎在我们的网站评价本次行程，也在 Google 上评价 Daily Red Sea。", siteReview: "评价您的行程", googleReview: "在 Google 上评价我们", independent: "评价完全自愿。推荐奖励与评价无关，不取决于是否评价或评分高低。", next: d => `探索更多${d}行程`, explore: "查看行程", signoff: "期待下一次冒险，\nDaily Red Sea 团队" },
};
