import type { BlogPost } from "./blog-posts";

// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const ryzeBlogPosts = [
  {
    "slug": "best-things-to-do-in-jeddah",
    "title": "7 Best Things to Do in Jeddah in 2026",
    "metaDescription": "Discover the best things to do in Jeddah in 2026, from Red Sea snorkeling and scuba diving to sunset cruises, Al-Balad and the Corniche.",
    "publishedAt": "2026-08-29T06:27:10.663Z",
    "heroImage": "/images/ryze-blog/best-things-to-do-in-jeddah.jpg",
    "relatedTourSlugs": [],
    "intro": "Best overall: take a Bayada snorkeling boat trip for a full Red Sea day. Best for first-time divers: choose the SSI Basic Diver experience. Best evening plan: cruise Obhur Bay at sunset. This 2026 guide combines Jeddah's strongest sea experiences with the city sights that fit around them, starting from the Daily Red Sea Jeddah trip hub. TL;DR • Bayada snorkeling is the best all-round Red Sea trip from Jeddah in 2026. • SSI Basic Diver is the best first scuba experience; no prior certification is required. • Certified divers should choose the two-dive boat trip, not the beginner session. • The Obhur Bay sunset cruise is the strongest short evening option. • Pair one sea trip with Al-Balad and the Corniche for a balanced Jeddah visit.",
    "sections": [
      {
        "heading": "Why this matters",
        "body": [
          "Jeddah is both a Red Sea gateway and a major city, so the best itinerary does not force you to choose between water and culture. The practical move in 2026 is to reserve one weather-dependent sea experience first, then place Al-Balad, the Corniche and other city stops around it.",
          "Google records about 2,400 monthly Saudi searches for “things to do in Jeddah,” while “Jeddah scuba diving” records about 480. That demand matches what visitors need: a clear decision between snorkeling, beginner diving, certified diving and a relaxed cruise, followed by a short list of city landmarks."
        ]
      },
      {
        "heading": "What makes the best Jeddah activity",
        "body": [
          "• Clear fit: The activity should match your certification, swimming confidence, available time and preferred pace.",
          "• Transparent duration: A 2-hour cruise and a 6-hour dive day solve different itinerary problems.",
          "• Known meeting point: Sea trips require check-in, identification or equipment fitting, so location details matter.",
          "• Included essentials: Equipment, tanks, refreshments and transport vary by trip and must be checked before booking.",
          "• Weather flexibility: Red Sea conditions can change routes, sites and departure times.",
          "• A strong alternative: Every sea plan needs an easy city option in case conditions change."
        ]
      },
      {
        "heading": "Jeddah activities at a glance",
        "body": [
          "| Rank | Activity | Best for | Standout feature | Current starting price | Key limitation |",
          "|---|---|---|---|---:|---|",
          "| 1 | Bayada snorkeling boat trip | Most visitors | Guided reef snorkeling | SAR 298 per person | You should be comfortable in open water |",
          "| 2 | SSI Basic Diver | First-time divers | Training plus one open-water dive | SAR 468 per person | Medical and flying-after-diving rules apply |",
          "| 3 | Certified diver boat trip | Qualified divers | Two guided Red Sea dives | SAR 340 per person | Certification required; rental gear costs extra |",
          "| 4 | Obhur Bay sunset yacht cruise | Couples and short stays | Golden-hour coastal views | SAR 102 per adult | It is a cruise, not a swimming or snorkeling trip |",
          "| 5 | Al-Balad | History and architecture | Historic streets and traditional buildings | Check current access | Outdoor walking in the heat can be tiring |",
          "| 6 | Jeddah Corniche and King Fahd's Fountain | Easy evening sightseeing | Waterfront views | Check current access | Fountain visibility depends on conditions and timing |",
          "| 7 | Al Rahma Mosque | Waterfront landmark | Mosque built over the Red Sea | Check current access | Respect worship times and dress requirements |"
        ]
      },
      {
        "heading": "1. Bayada snorkeling boat trip: best overall Red Sea day",
        "body": [
          "The Bayada snorkeling trip is the best all-round choice because it delivers a real boat day without requiring scuba certification. The scheduled experience runs for 5–6 hours and visits a rotating Bayada-area snorkeling site selected according to sea and weather conditions.",
          "A professional snorkeling instructor, mask, snorkel and fins are included, along with snacks and drinks. The meeting point is Al-Haddad Scuba Shop, and sailing time to the day's site is about 30–40 minutes according to the published itinerary.",
          "Bayada snorkeling pros:",
          "• No scuba certification is required.",
          "• The boat trip includes snorkeling equipment and instructor support.",
          "• The 5–6-hour format gives the Red Sea enough space in your day.",
          "• A rotating site plan lets the operator respond to conditions.",
          "Bayada snorkeling cons:",
          "• You need to feel comfortable in open water.",
          "• The exact reef site is not guaranteed in advance.",
          "• The trip occupies most of the morning and early afternoon.",
          "Best for: Travelers who want one clear Red Sea experience and prefer snorkeling to scuba training. Verdict: Buy."
        ]
      },
      {
        "heading": "2. SSI Basic Diver: best for first-time scuba divers",
        "body": [
          "The SSI Basic Diver experience is designed for people without a dive certification. It combines a theory session, confined-water skills and one instructor-led open-water dive lasting about 30–45 minutes.",
          "The full program takes approximately 4 hours. The published maximum depth is 12 metres, but the instructor decides the actual depth and duration based on participant comfort, conditions and safety.",
          "SSI Basic Diver pros:",
          "• It is built for first-time and non-certified divers.",
          "• Equipment and instructor supervision are included.",
          "• Confined-water practice comes before the open-water dive.",
          "• The program provides a structured introduction rather than a rushed drop-in.",
          "SSI Basic Diver cons:",
          "• Medical conditions must be disclosed and can affect eligibility.",
          "• You must not fly for at least 24 hours after diving.",
          "• Snacks, towels and transport are not listed as included.",
          "Best for: Curious beginners who want a supervised first dive rather than a snorkeling trip. Verdict: Buy if your health and flight schedule allow it."
        ]
      },
      {
        "heading": "3. Certified diver boat trip: best for qualified divers",
        "body": [
          "The certified diver boat trip is a separate product for divers who can show recognized certification. It includes two guided boat dives at a wreck or coral site, with the exact location chosen from the operator's available sites and the day's conditions.",
          "The scheduled duration is 6–8 hours. Tanks, weight belts, snacks and drinks are included; other diving equipment is available to rent separately rather than included in the base booking.",
          "Certified dive trip pros:",
          "• Two guided dives make better use of a qualified diver's day.",
          "• Wreck and coral locations are both possible.",
          "• Tanks and weight belts are included.",
          "• The operator caps the trip at 20 divers.",
          "Certified dive trip cons:",
          "• Non-certified travelers cannot join as divers.",
          "• Full equipment rental costs extra.",
          "• The 6–8-hour window requires a flexible afternoon.",
          "Best for: Certified divers who want a proper Jeddah Red Sea dive day. Verdict: Buy if your certification and recent-diving readiness are current."
        ]
      },
      {
        "heading": "4. Obhur Bay sunset cruise: best evening activity",
        "body": [
          "The Jeddah sunset yacht cruise is the best fit when you want the sea without committing most of the day. The published experience lasts approximately 2–2.5 hours including check-in and sails through Obhur Bay during golden hour.",
          "Shorouk Sat has three outdoor viewing decks, an air-conditioned indoor salon and two restrooms. Sandwiches plus hot and cold drinks are included, and guests must bring valid identification for Coast Guard clearance.",
          "Sunset cruise pros:",
          "• The short format fits after daytime sightseeing.",
          "• Open decks provide clear coastal and sunset views.",
          "• The indoor salon gives you an air-conditioned option.",
          "• Adult, child and infant categories are listed.",
          "Sunset cruise cons:",
          "• Transport to the meeting point is not included.",
          "• This is not a snorkeling or swimming excursion.",
          "• Late arrival can invalidate the booking under the displayed operator terms.",
          "Best for: Couples, families and short-stay visitors who want a low-effort Red Sea evening. Verdict: Buy for sunset; skip if your priority is time in the water."
        ]
      },
      {
        "heading": "5. Al-Balad: best for Jeddah's historic character",
        "body": [
          "Al-Balad is the city stop that gives the clearest contrast with a modern marina or Red Sea trip. Its traditional buildings, old streets and market atmosphere make it the strongest heritage component in a 2026 Jeddah itinerary.",
          "Go when the temperature supports walking and give yourself room to explore rather than treating the district as a quick photo stop. Opening access for individual buildings and museums can change, so verify the places you specifically want to enter.",
          "Best for: Architecture, street photography and local history. Verdict: Buy time for it; do not compress it between two fixed bookings."
        ]
      },
      {
        "heading": "6. Corniche and King Fahd's Fountain: best easy evening circuit",
        "body": [
          "Jeddah Corniche is the simplest place to combine a waterfront walk with views toward King Fahd's Fountain. Visit Saudi identifies the fountain as a Jeddah icon rising over 300 metres, while the Corniche provides the broad coastal setting around it.",
          "Plan this as a flexible evening rather than a timed ticketed attraction. Wind, visibility and fountain operation can affect what you see, but the waterfront still works as a relaxed city stop.",
          "Best for: A light evening after a boat or dive trip. Verdict: Buy the time, but keep the schedule flexible."
        ]
      },
      {
        "heading": "7. Al Rahma Mosque: best Red Sea landmark",
        "body": [
          "Al Rahma Mosque, often called the Floating Mosque, stands above the Red Sea and is one of Jeddah's best-known waterfront landmarks. It works naturally before or after a northern Corniche or Obhur plan.",
          "This is an active place of worship, not only a sightseeing backdrop. Dress respectfully, avoid disrupting prayer and check access conditions before making a special journey.",
          "Best for: Visitors who want a recognisable Jeddah waterfront landmark. Verdict: Visit respectfully."
        ]
      },
      {
        "heading": "How we ranked these activities",
        "body": [
          "The ranking prioritizes distinct Jeddah experiences, clear booking information and usefulness within a real itinerary. Bookable Daily Red Sea activities rank highest because their duration, meeting points, inclusions and participant requirements are published; city sights follow according to how well they complement a Red Sea day.",
          "The list is not a claim that every traveler should do all seven. In 2026, one sea experience plus two or three city stops is a stronger plan than rushing through the entire table."
        ]
      },
      {
        "heading": "Which Jeddah activities should you choose?",
        "body": [
          "Choose Bayada snorkeling if you want the broadest Red Sea day without scuba certification. Choose SSI Basic Diver if your main goal is a first dive, and choose the certified boat trip only if you already hold a recognized qualification. Choose the Obhur Bay yacht cruise when time is limited or sunset matters more than entering the water.",
          "For the city portion, default to Al-Balad and the Corniche. Add Al Rahma Mosque or Jeddah Waterfront if your route makes sense, then keep an indoor option for the hottest part of the day.",
          "Daily Red Sea is the best fit for travelers comparing bookable Jeddah sea trips with clear schedules, meeting details and published inclusions. The city sights need no forced package; combine them around your fixed water activity."
        ]
      },
      {
        "heading": "One last thing",
        "body": [
          "Do not schedule a flight within 24 hours after scuba diving. That single timing rule can decide whether the beginner or certified dive trip fits your 2026 itinerary; snorkeling and the sunset cruise do not create the same flying-after-diving constraint."
        ]
      },
      {
        "heading": "Related guides",
        "body": [
          "• Compare Jeddah diving and snorkeling experiences"
        ]
      }
    ],
    "faqs": [
      {
        "question": "What are the best things to do in Jeddah in 2026?",
        "answer": "The best things to do in Jeddah in 2026 are a Bayada snorkeling trip, beginner or certified scuba diving, an Obhur Bay sunset cruise, Al-Balad and the Corniche. Choose one sea activity, then add city sights around its schedule."
      },
      {
        "question": "Can beginners scuba dive in Jeddah?",
        "answer": "Yes. The SSI Basic Diver program is designed for first-time, non-certified participants and includes theory, confined-water skills and one supervised open-water dive."
      },
      {
        "question": "What is the best Red Sea trip from Jeddah without diving?",
        "answer": "The Bayada snorkeling boat trip is the best all-round option without scuba certification. It includes guided snorkeling, equipment, snacks and drinks on a 5–6-hour outing."
      },
      {
        "question": "What should certified divers book in Jeddah?",
        "answer": "Certified divers should book the two-dive boat trip. It requires proof of certification and includes two guided dives, tanks, weight belts, snacks and drinks."
      },
      {
        "question": "Is there a short boat trip in Jeddah?",
        "answer": "Yes. The Obhur Bay sunset yacht cruise lasts about 2–2.5 hours including check-in, making it the easiest sea activity to fit into an evening."
      },
      {
        "question": "What can I do in Jeddah if the sea trip is cancelled?",
        "answer": "Use Al-Balad, the Corniche, Al Rahma Mosque, Jeddah Waterfront or an indoor mall as alternatives. Keep at least one flexible city block because sea conditions can change."
      },
      {
        "question": "How many days do I need for Jeddah?",
        "answer": "Two days give you a practical split: one Red Sea experience and one city-focused day. A one-day visit can still work if you choose either a half-day sea trip or the short sunset cruise."
      },
      {
        "question": "Where can I compare Jeddah diving and snorkeling trips?",
        "answer": "Daily Red Sea lists beginner diving, certified diving and Bayada snorkeling with durations, meeting points and inclusions in one Jeddah diving and snorkeling collection."
      }
    ]
  }
] satisfies BlogPost[];
