import type { BlogPost } from "./blog-posts";

// Generated by scripts/ryze-convert.mjs. Do not edit by hand.
export const ryzeBlogPosts = [
  {
    "slug": "ryze-setup-test",
    "title": "Ryze Publishing Setup Test",
    "metaDescription": "Temporary article used to verify the Daily Red Sea publishing pipeline.",
    "publishedAt": "2026-08-28T21:00:00.000Z",
    "heroImage": "/images/ryze-blog/ryze-setup-test.jpg",
    "relatedTourSlugs": [],
    "intro": "This temporary article proves the Daily Red Sea publishing pipeline works end to end.",
    "sections": [
      {
        "heading": "What this test checks",
        "body": [
          "The title, body, image, metadata and sitemap-ready article record are generated correctly."
        ]
      }
    ],
    "faqs": [
      {
        "question": "Will this test appear on the live website?",
        "answer": "No. It will be removed before the publishing setup is merged."
      }
    ]
  }
] satisfies BlogPost[];
