import { NextRequest, NextResponse } from "next/server";
import { adminRoles, isAdminOwner } from "@/lib/admin-auth";
import { createRequiredAdminClient } from "@/utils/supabase/admin";
import { createClient } from "@/utils/supabase/server";

async function owner(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();return{user,allowed:isAdminOwner(user)};}
export async function GET(){const{allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const admin=createRequiredAdminClient();const{data,error}=await admin.from("admin_profiles").select("*").order("created_at");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({staff:data});}
export async function POST(request:NextRequest){const{allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const body=await request.json();const email=String(body.email||"").trim().toLowerCase();const role=String(body.role||"");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!adminRoles.includes(role as never))return NextResponse.json({error:"Valid email and role required"},{status:400});const admin=createRequiredAdminClient();const{data,error}=await admin.auth.admin.inviteUserByEmail(email,{data:{full_name:String(body.name||email)},redirectTo:`${process.env.NEXT_PUBLIC_SITE_URL||"https://dailyredsea.com"}/admin/login`});if(error)return NextResponse.json({error:error.message},{status:400});if(data.user){await admin.auth.admin.updateUserById(data.user.id,{app_metadata:{admin_role:role}});await admin.from("admin_profiles").upsert({id:data.user.id,email,display_name:String(body.name||email),role,active:true});}return NextResponse.json({invited:true});}
export async function PATCH(request:NextRequest){const{allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const body=await request.json();const id=String(body.id||"");const role=String(body.role||"");const active=body.active!==false;if(!adminRoles.includes(role as never))return NextResponse.json({error:"Invalid role"},{status:400});const admin=createRequiredAdminClient();const{error}=await admin.from("admin_profiles").update({role,active,updated_at:new Date().toISOString()}).eq("id",id);if(error)return NextResponse.json({error:error.message},{status:400});await admin.auth.admin.updateUserById(id,{app_metadata:{admin_role:active?role:null},ban_duration:active?"none":"876000h"});return NextResponse.json({updated:true});}
