import { NextRequest, NextResponse } from "next/server";
import { adminRoles, isAdminOwner } from "@/lib/admin-auth";
import { createRequiredAdminClient } from "@/utils/supabase/admin";
import { createClient } from "@/utils/supabase/server";
import { passwordPolicyError } from "@/lib/password-policy";

async function owner(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();return{user,allowed:isAdminOwner(user)};}
export async function GET(){const{allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const admin=createRequiredAdminClient();const{data,error}=await admin.from("admin_profiles").select("*").order("created_at");if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({staff:data});}
export async function POST(request:NextRequest){const{user,allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const body=await request.json();const email=String(body.email||"").trim().toLowerCase();const role=String(body.role||"");const mode=body.mode==="create"?"create":"invite";const password=String(body.password||"");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!adminRoles.includes(role as never))return NextResponse.json({error:"Valid email and role required"},{status:400});if(mode==="create"){const passwordError=passwordPolicyError(password);if(passwordError)return NextResponse.json({error:passwordError},{status:400});}const admin=createRequiredAdminClient();const result=mode==="create"?await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{full_name:String(body.name||email)},app_metadata:{admin_role:role}}):await admin.auth.admin.inviteUserByEmail(email,{data:{full_name:String(body.name||email)},redirectTo:`${process.env.NEXT_PUBLIC_SITE_URL||"https://dailyredsea.com"}/admin/reset-password`});if(result.error)return NextResponse.json({error:result.error.message},{status:400});if(result.data.user){await admin.auth.admin.updateUserById(result.data.user.id,{app_metadata:{admin_role:role}});await admin.from("admin_profiles").upsert({id:result.data.user.id,email,display_name:String(body.name||email),role,active:true});await admin.from("admin_audit_log").insert({actor_id:user!.id,actor_email:user!.email?.toLowerCase(),action:mode,resource_type:"admin_user",resource_id:result.data.user.id,summary:`${mode==="create"?"Created":"Invited"} ${email} as ${role}`,after_data:{email,role,active:true}});}return NextResponse.json({created:mode==="create",invited:mode==="invite"});}
export async function PATCH(request:NextRequest){const{user,allowed}=await owner();if(!allowed)return NextResponse.json({error:"Owner access required"},{status:403});const body=await request.json();const id=String(body.id||"");const role=String(body.role||"");const active=body.active!==false;if(!adminRoles.includes(role as never))return NextResponse.json({error:"Invalid role"},{status:400});const admin=createRequiredAdminClient();const{data:before}=await admin.from("admin_profiles").select("email,role,active").eq("id",id).single();const{error}=await admin.from("admin_profiles").update({role,active,updated_at:new Date().toISOString()}).eq("id",id);if(error)return NextResponse.json({error:error.message},{status:400});await admin.auth.admin.updateUserById(id,{app_metadata:{admin_role:active?role:null},ban_duration:active?"none":"876000h"});await admin.from("admin_audit_log").insert({actor_id:user!.id,actor_email:user!.email?.toLowerCase(),action:"update",resource_type:"admin_user",resource_id:id,summary:`Updated ${before?.email||"staff account"}: ${before?.role||"unknown"} to ${role}${active?"":" (disabled)"}`,before_data:before,after_data:{email:before?.email,role,active}});return NextResponse.json({updated:true});}
