"use client";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Trash2, X } from "lucide-react";
type Booking={id:string;reference:string;customer_name:string;tour_name:string|null;amount:number|string;currency:string;date:string|null};
type Expense={id:string;description:string;amount:number|string;currency:string;expense_date:string;category:string|null};
type Assignment={id:string;assignment_type:string;staff_member_id:string|null;supplier_id:string|null};
type Detail={expenses:Expense[];assignments:Assignment[];staff:{id:string;name:string;staff_type:"guide"|"driver"}[];suppliers:{id:string;name:string;type?:string}[]};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Africa/Cairo"});
export default function BookingDetailPanel({booking,onClose}:{booking:Booking;onClose:()=>void}){
 const[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const[form,setForm]=useState({id:"",description:"",amount:"",expense_date:today(),category:""});
 const load=async()=>{const r=await fetch(`/api/admin/bookings/${booking.id}/detail`,{cache:"no-store"}),d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load details.");setDetail(d)};useEffect(()=>{fetch(`/api/admin/bookings/${booking.id}/detail`,{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not load details.");return d}).then(setDetail).catch(e=>setError(e.message))},[booking.id]);
 const cost=useMemo(()=>detail?.expenses.reduce((s,e)=>s+Number(e.amount),0)||0,[detail]);const money=(n:number)=>new Intl.NumberFormat("en",{style:"currency",currency:booking.currency||"USD"}).format(n);const assigned=(k:string)=>detail?.assignments.find(a=>a.assignment_type===k);
 async function assign(k:"guide"|"driver"|"supplier",v:string){if(!v)return;setBusy(true);try{const key=k==="supplier"?"supplier_id":"staff_member_id",r=await fetch(`/api/admin/bookings/${booking.id}/detail`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({assignment_type:k,[key]:v})}),d=await r.json();if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(form.id?`/api/admin/expenses/${form.id}`:"/api/admin/expenses",{method:form.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,date:form.expense_date,booking_id:booking.id,currency:booking.currency})}),d=await r.json();if(!r.ok)throw new Error(d.error);setForm({id:"",description:"",amount:"",expense_date:today(),category:""});await load()}catch(e){setError(e instanceof Error?e.message:"Save failed.")}finally{setBusy(false)}}
 async function remove(e:Expense){if(!confirm(`Delete expense “${e.description}”?`))return;const r=await fetch(`/api/admin/expenses/${e.id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();setError(d.error)}else await load()}
 return <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/50" role="dialog" aria-modal="true"><div className="h-full w-full max-w-3xl overflow-y-auto bg-slate-50 p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-widest text-blue-700">Booking detail</p><h2 className="font-mono text-2xl font-black">{booking.reference}</h2><p>{booking.customer_name} · {booking.tour_name||"Transfer"} · {booking.date||"Date pending"}</p></div><button onClick={onClose} aria-label="Close" className="rounded-xl border bg-white p-2"><X/></button></div>{error?<p className="mt-4 rounded-xl bg-rose-50 p-3 text-rose-700">{error}</p>:null}{!detail?<p className="mt-8">Loading booking details…</p>:<div className="mt-6 space-y-6">
 <section className="rounded-2xl border-2 border-cyan-200 bg-cyan-50 p-5"><b className="text-xs uppercase tracking-wider text-cyan-900">Customer-visible</b><p className="mt-1 text-sm">Only the selected guide or driver name is exposed externally.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{(["guide","driver"] as const).map(k=><label key={k} className="text-sm font-semibold capitalize">{k}<select disabled={busy} value={assigned(k)?.staff_member_id||""} onChange={e=>assign(k,e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-2"><option value="">Not assigned</option>{detail.staff.filter(s=>s.staff_type===k).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>)}</div></section>
 <section className="rounded-2xl border-2 border-amber-200 bg-amber-50 p-5"><b className="text-xs uppercase tracking-wider text-amber-900">Internal only — never customer-facing</b><label className="mt-4 block text-sm font-semibold">Supplier<select disabled={busy} value={assigned("supplier")?.supplier_id||""} onChange={e=>assign("supplier",e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-2"><option value="">Not assigned</option>{detail.suppliers.map(s=><option key={s.id} value={s.id}>{s.name} · {s.type||"other"}</option>)}</select></label><div className="mt-4 grid grid-cols-3 gap-2 text-center">{[["Revenue",Number(booking.amount)],["Cost",cost],["Margin",Number(booking.amount)-cost]].map(([l,n])=><div key={String(l)} className="rounded-xl bg-white p-3"><p className="text-xs text-slate-500">{l}</p><b>{money(Number(n))}</b></div>)}</div><h3 className="mt-6 font-bold">Expense line items</h3><div className="mt-2 space-y-2">{detail.expenses.map(e=><div key={e.id} className="flex justify-between rounded-xl bg-white p-3 text-sm"><div><b>{e.description}</b><p className="text-xs text-slate-500">{e.expense_date} · {e.category||"Uncategorised"}</p></div><div className="flex items-center gap-2"><b>{money(Number(e.amount))}</b><button onClick={()=>setForm({id:e.id,description:e.description,amount:String(e.amount),expense_date:e.expense_date,category:e.category||""})} aria-label="Edit expense"><Pencil size={16}/></button><button onClick={()=>remove(e)} aria-label="Delete expense" className="text-rose-700"><Trash2 size={16}/></button></div></div>)}</div><form onSubmit={save} className="mt-4 grid gap-2 sm:grid-cols-2"><input required minLength={2} placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="rounded-xl border p-2"/><input required type="number" min=".01" step=".01" placeholder="Amount" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="rounded-xl border p-2"/><input required type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})} className="rounded-xl border p-2"/><input placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded-xl border p-2"/><button disabled={busy} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 p-2 font-bold text-white sm:col-span-2"><Plus size={16}/>{form.id?"Update expense":"Add expense"}</button></form></section></div>}</div></div>
}
