"use client";
import { useState } from "react";
import { Activity, RefreshCw, Users } from "lucide-react";

type Row=Record<string,string|number>;
type Report={configured:true;from:string;to:string;timeZone:string;summary:{sessions:number;users:number;activeUsers:number;newUsers:number;pageViews:number;averageSessionDuration:number;bounceRate:number;bookingEvents:number;bookingConversionRate:number;liveUsers:number};geography:Row[];sources:Row[];pages:Row[];devices:Row[]}|{configured:false;missing:string[]};
const iso=(date:Date)=>date.toISOString().slice(0,10);
const initialTo=iso(new Date());const start=new Date();start.setUTCDate(start.getUTCDate()-29);const initialFrom=iso(start);

export default function GoogleAnalyticsPanel(){const[from,setFrom]=useState(initialFrom);const[to,setTo]=useState(initialTo);const[data,setData]=useState<Report|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const response=await fetch(`/api/admin/google-analytics?from=${from}&to=${to}`,{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not load visitor analytics.");setData(result);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load visitor analytics.");}finally{setLoading(false);}}
return <section id="visitor-analytics" className="mt-8 scroll-mt-6 rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex items-start gap-3"><Activity className="mt-1 text-violet-700"/><div><h2 className="text-2xl font-bold">Website visitors</h2><p className="mt-1 text-sm text-slate-500">Live and historical traffic from Google Analytics 4. Counts include visitors who accepted Analytics consent.</p></div></div><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-bold text-slate-500">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2 text-sm text-slate-900"/></label><label className="text-xs font-bold text-slate-500">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-1 block rounded-xl border px-3 py-2 text-sm text-slate-900"/></label><button onClick={load} disabled={loading||from>to} className="inline-flex items-center gap-2 rounded-xl bg-violet-700 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><RefreshCw size={16} className={loading?"animate-spin":""}/>{loading?"Loading…":"Load analytics"}</button></div></div>
{error?<p className="mt-5 rounded-xl bg-rose-50 p-4 text-sm font-semibold text-rose-800">{error}</p>:null}
{data&&data.configured===false?<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900">Add the missing Vercel setting: <code>{data.missing.join(", ")}</code>, then redeploy.</p>:null}
{data?.configured?<><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8"><Metric label="Live now" value={data.summary.liveUsers}/><Metric label="Sessions" value={data.summary.sessions}/><Metric label="Visitors" value={data.summary.users}/><Metric label="Active users" value={data.summary.activeUsers}/><Metric label="New users" value={data.summary.newUsers}/><Metric label="Page views" value={data.summary.pageViews}/><Metric label="Avg. session" value={`${Math.round(data.summary.averageSessionDuration)}s`}/><Metric label="Booking rate" value={`${data.summary.bookingConversionRate.toFixed(2)}%`}/></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Table title="Countries and cities" columns={["country","city","sessions","users"]} rows={data.geography}/><Table title="Traffic sources" columns={["channel","source","medium","sessions"]} rows={data.sources}/><Table title="Most visited pages" columns={["path","title","views","users"]} rows={data.pages}/><Table title="Devices" columns={["device","sessions","users"]} rows={data.devices}/></div><p className="mt-4 text-xs text-slate-500">Booking rate = {data.summary.bookingEvents} booking_complete events ÷ {data.summary.sessions} sessions. Realtime covers approximately the last 30 minutes.</p></>:null}</section>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-violet-50 p-4"><Users size={16} className="text-violet-700"/><p className="mt-2 text-xs font-bold text-violet-700">{label}</p><p className="mt-1 text-2xl font-black">{typeof value==="number"?value.toLocaleString():value}</p></div>}
function Table({title,columns,rows}:{title:string;columns:string[];rows:Row[]}){return <div className="overflow-hidden rounded-2xl border"><h3 className="bg-slate-50 p-4 font-black">{title}</h3><div className="max-h-80 overflow-auto"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-white text-slate-500"><tr>{columns.map(column=><th key={column} className="p-3 capitalize">{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t">{columns.map(column=><td key={column} className="max-w-56 truncate p-3" title={String(row[column]??"")}>{typeof row[column]==="number"?Number(row[column]).toLocaleString():String(row[column]??"")}</td>)}</tr>)}</tbody></table>{!rows.length?<p className="p-5 text-center text-sm text-slate-500">No data for this period.</p>:null}</div></div>}
